### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by habibun** [ld-web/medium-sf-di-solid-geocoding#2]
https://github.com/ld-web/medium-sf-di-solid-geocoding/blob/79dfba0810190b58a026e8c45dca8d112131f85e/src/Entity/Destination.php#L31

I do not understand this line, could you please clarify, thanks

**Comment by ld-web** [comment]
Oops, since this code came from another project, it looks like I didn't clean it well enough.
I'll remove this and push to fix it, thanks
